Idx = 1
KeyStoreDir = "/root/go/src/github.com/wolkdb/cloudstore/wolk/cloud/credentials/keystore"
GenesisFile = "/root/go/src/github.com/wolkdb/cloudstore/wolk/cloud/credentials/genesis.json"
DataDir = "/tmp/wolk"
Provider = "leveldb"
Password = "Vis42mod!"
Region = "NA"
AmazonCredentials = "/root/go/src/github.com/wolkdb/cloudstore/wolk/cloud/credentials/credentials"
AmazonRegion = "ap-northeast-2"
AmazonWCU = 50
AmazonRCU = 40
GoogleDatastoreCredentials  = "/root/go/src/github.com/wolkdb/cloudstore/wolk/cloud/credentials/google.json"
GoogleDatastoreProject = "crosschannel-1307"
GoogleBigTableCredentials  = "/root/go/src/github.com/wolkdb/cloudstore/wolk/cloud/credentials/google-bigtable-2018.json"
GoogleBigTableProject = "colorfulnotion-2018"
GoogleBigTableInstance = "colorfulnotion"
Leveldb = true
UseCache = 0
