apiVersion: v1
kind: Service
metadata:
  labels:
    run: example-app
  name: example-app
  namespace: default
spec:
  ports:
  - nodePort: 30000
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: example-app
  sessionAffinity: None
  type: NodePort