#!/usr/bin/php -q
<?php

include "/var/www/vhosts/mdotm.com/include/storage.php";

$hname = php_uname('n');
$sa = explode(".", $hname);
$server = array_shift($sa);

$fn_log = "/var/log/git.log";
$fn_err = "/var/log/git.err";
$out = file_get_contents($fn_log);
$err = file_get_contents($fn_err);

$cmd = "cd /var/www/vhosts/mdotm.com/; git status";
$a = array();
exec($cmd, $a);

$gitstatus = implode("\n", $a);

$logDT = date("Y-m-d H:i:s", filemtime($fn_log));
$storage = new Storage;
$storage->getMdotmDatabase();
$sql = "update servers set gitpullDT = Now(), gitstatus = '".mysql_real_escape_string($gitstatus)."', gitpull_result = '".mysql_real_escape_string($out)."', gitpull_error = '".mysql_real_escape_string($err)."', gitpullDT = '$logDT' where hostname = '$server' ";
if ( mysql_query($sql) ) {
   echo $sql."\n";
} else
  echo mysql_error().$sql;

?>