#!/usr/bin/php
<?
include "/var/www/vhosts/mdotm.com/include/storage.php";
include "/var/www/vhosts/mdotm.com/include/www-servers.php";
include_once "/var/www/vhosts/mdotm.com/include/communications.php";

$storage = new Storage;
$storage->getMdotmDatabase();

// www6001
echo "CrossChannel Data Pushcode\n";
echo "git update www6001-> /var/www/vhosts/www.wolk.com\n\n";
$c = "ssh -q www6001 'sh /var/www/vhosts/mdotm.com/scripts/utils/git_for_www.wolk.com.sh 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
echo "$c\n";
$output = array();
exec($c, $output);
print_r($output);
echo "\n";

// www6005
echo "CrossChannel Data Pushcode\n";
echo "git update www6005-> /var/www/vhosts/www.wolk.com\n\n";
$c = "ssh -q www6005 'sh /var/www/vhosts/mdotm.com/scripts/utils/git_for_www.wolk.com.sh 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
echo "$c\n";
$output = array();
exec($c, $output);
print_r($output);  
echo "\n"; 

// www6006
echo "CrossChannel Data Pushcode\n";
echo "git update www6006-> /var/www/vhosts/www.wolk.com\n\n";
$c = "ssh -q www6006 'sh /var/www/vhosts/mdotm.com/scripts/utils/git_for_www.wolk.com.sh 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
echo "$c\n";
$output = array();
exec($c, $output);
print_r($output);  
echo "\n";

// www6002
echo "CrossChannel Data Pushcode\n";
echo "git update www6002-> /var/www/vhosts/www.wolk.com\n\n";
$c = "ssh -q www6002 'sh /var/www/vhosts/mdotm.com/scripts/utils/git_for_www.wolk.com.sh 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
echo "$c\n";
$output = array();
exec($c, $output);
print_r($output);  
echo "\n";

/*
//$servers[] = "www6002"; // add www6002   to update www6002
foreach ($servers as $server) {
  if (strstr($hostname[$server], $instanceGroup)) { echo "\n$hostname[$server] $instanceGroup\n";
    $h = "git reset --hard HEAD~1;";
    $c = "ssh $server 'cd /var/www/vhosts/crosschannel.com/bidder/bin && git fetch upstream && git merge upstream/master && php goservice.php $service 2> /var/log/git.err  >
 /var/log/git.log' > /dev/null 2>&1 &";
    echo "$c\n";
    $output = array();
    exec($c, $output);  
    echo "\n";
  }
}
for ($i=0; $i<3; $i++) {
  sleep(1);
  echo "[$i]";
}
*/

$today = date("F j, Y, g:i a T"); 
$mail_subject = "CODE PUSH www.wolk.com (" . $name . ") - $today";
$mail_body = "Code was pushed using pushwolk to www6005 + www6006 at " . $today . " to " . $cluster . ".  Details below:\n\n";
$mail_body .= "Pushed by: " . $name . "\n";
$mail_body .= "QA by: " . $qa . "\n";
$mail_body .= "Reason: " . $reason . "\n\n";
  
$mail_return = crosschannel_mail("adops@crosschannel.com", "engineering@crosschannel.com", $mail_subject, $mail_body);
if ($mail_return) echo("Message successfully sent!!\n");
?>
