#!/usr/bin/php
<?
include "storage.php";
include "www-servers.php";
include_once "communications.php";

$storage = new Storage;
$storage->getMdotmDatabase();

//$sql = "select hostname, publicip from servers where (hostname like 'www8%' or hostname like 'www2%' or hostname like 'www9%' or hostname like 'wwwa%' or hostname like 'www6%' or hostname like 'log%' or hostname like 'ha%') and status = 'RUNNING' and length(publicip) > 0";
$sql = "select hostname, privateip, publicip from servers where (hostname like 'www8%' or hostname like 'www2%' or hostname like 'wwwa%' or hostname like 'www6%' or hostname like 'ha%' or hostname like '%ccdex%') and status = 'RUNNING' and length(publicip) and length(privateip) > 0";
if ( $res = mysql_query($sql) ) {
	while ( $a = mysql_fetch_object($res) ) {

		// log, seed           in $www_servers (include "www-servers.php";)
		// www6001, www6002    manually added in this file

		switch ( substr($a->hostname, 0, 4) ) {
			case "www6":
				$instanceGroup = "cn";
				break;
			case "www2":
				$instanceGroup = "ea";
				break;
			case "www8":
				$instanceGroup = "eu";
				break;
			case "wwwa":
				$instanceGroup = "as";
				break;
			case "ccdex":
				$instanceGroup = "ccdex";
				break;
		}
		 
		switch ( substr($a->hostname, 0, 3) ) {
			case "ha6":
				$instanceGroup = "cn";
				break;
            case "ha2":
                $instanceGroup = "ea";
                break;
			case "ha8":
				$instanceGroup = "eu";
				break;
			case "haa":
				$instanceGroup = "as";
				break;
		}

		$servers[$instanceGroup][] = $a->privateip;
	}
}

foreach ($servers as $instanceGroup => $ips) {
  $www_servers[$instanceGroup] = implode("|", $ips); 
}

function readin($prompt = ''){
    echo $prompt;
    return rtrim( fgets( STDIN ), "\n" );
}

function get_name() 
{
  $name = readin("Who are you? ");
  if(empty($name)){
    echo "\nI need to know who you are!\n";
    get_name();
  } else
    return $name;
}

function get_qa() 
{
  $qa = readin("Who QA? ");
  if(empty($qa)){
    echo "\nI need to know who QA!\n";
    get_qa();
  } else
    return $qa;
}

function prompt_silent($prompt = "Enter Password:") 
{
  $command = "/usr/bin/env bash -c 'echo OK'";
  if (rtrim(shell_exec($command)) !== 'OK') {
    trigger_error("Can't invoke bash");
    return;
  }
  $command = "/usr/bin/env bash -c 'read -s -p \""
    . addslashes($prompt)
    . "\" mypassword && echo \$mypassword'";
  $password = rtrim(shell_exec($command));
  echo "\n";
  return $password;
}


function get_reason() {
  $reason = readin("Why are you pushing? ");
  if(empty($reason)){
    echo "\nPlease supply a reason.\n";
    get_reason();
  } else
    return $reason;
}

function smoketest() 
{
  // test for echo in the file
  echo " Smoketest: echo...";
  $protected = array( // "c.php" => "/var/www/vhosts/mdotm.com/httpdocs/ads/c.php", 
  		     "api.php" => "/var/www/vhosts/mdotm.com/httpdocs/ads/api.php", 
		     "mdotmfeed-pico.php" => "/var/www/vhosts/mdotm.com/httpdocs/ads/mdotmfeed-pico.php", 
		     "feed.php" => "/var/www/vhosts/mdotm.com/httpdocs/ads/feed.php", 
		     "adxbid.php" => "/var/www/vhosts/mdotm.com/httpdocs/ads/adxbid.php", 
		     "mopubbid2_3" => "/var/www/vhosts/mdotm.com/httpdocs/ads/mopubbid2_3.php");
  foreach ($protected as $key => $file_name) {
    $echo_result = exec("grep echo $file_name  | wc -l");
    $No_echo_error = ($echo_result == 0);
    
    if($No_echo_error) {     
        echo "[$key]";
    } else { // syntax fail
      echo "FAIL\n";
      return "File name -> $file_name : ".$echo_result. " echos present -- use showdebug (from storage.php) instead of echo and print statements!";
    }
  }
  echo " Pass\n";
  
  // syntax
  echo " Test: syntax...";
  $syntax_list = array("storage" => "/var/www/vhosts/mdotm.com/include/storage.php", 
		       "logger" => "/var/www/vhosts/mdotm.com/include/logger.php",                         
		       "c" => "/var/www/vhosts/mdotm.com/httpdocs/ads/c.php", 
		       "api" => "/var/www/vhosts/mdotm.com/httpdocs/ads/api.php", 
		       "mdotmfeed-pico" => "/var/www/vhosts/mdotm.com/httpdocs/ads/mdotmfeed-pico.php", 
		       "feed" => "/var/www/vhosts/mdotm.com/httpdocs/ads/feed.php", 
		       "adxbid" => "/var/www/vhosts/mdotm.com/httpdocs/ads/adxbid.php", 
		       "mopub" => "/var/www/vhosts/mdotm.com/httpdocs/ads/mopubbid2_3.php", 
		       "networkmodel" => "/var/www/vhosts/mdotm.com/httpdocs/system/application/models/networkmodel.php",
		       "accountmodel" => "/var/www/vhosts/mdotm.com/httpdocs/system/application/models/accountmodel.php",
		       "campaignmodel" => "/var/www/vhosts/mdotm.com/httpdocs/system/application/models/campaignmodel.php",
		       "affiliatemodel" => "/var/www/vhosts/mdotm.com/httpdocs/system/application/models/affiliatemodel.php"                        
		       );
  foreach ($syntax_list as $key => $file_name) {     
    if ( strstr($file_name, "php") ) {
      $syntax_result = exec("php -l $file_name  --option 2>&1");    
      $No_syntax_error = stristr($syntax_result, "No syntax errors detected in");
      if ($No_syntax_error) {     
	echo "[$key]";
      } else { // syntax fail
	echo "FAIL\n";
	return "File name -> $file_name : php -l Fail : $syntax_result";
      }
    }
  }    
  echo " Pass\n";
       
  return false;
}


if ( isset($argv[1]) ) {
  $cluster = $argv[1];
} else {
  echo "CrossChannel Pushcode - Usage : pushcode {all|seed|log|cn|ea|eu|as}\n";
}

if ( $cluster == "all" ) {
  $servers = explode("|", implode("|", array(//					     
					     $www_servers["cn"], //www6xxx	
					     $www_servers["ea"], //www2xxx	
					     $www_servers["eu"], //www8xxx	
					     $www_servers["as"], //wwwaxxx	
					     $www_servers["ccdex"], //ccdex	
					     $www_servers["ha2"], //ha2	
					     $www_servers["ha6"], //ha6	
					     $www_servers["ha8"], //ha8	
					     $www_servers["haa"] //haa	
					     )
				  ));
} else if ( isset($www_servers[$cluster]) ) {
  $servers = explode("|", $www_servers[$cluster]);
} else {
  echo "Invalid cluster specified! " . $cluster . " does not exist. Options are: \n";
  print_r(array_keys($www_servers));
  exit;
}

if($argv[2] == "-s") {
  $name = "Auto";
  $qa = "Auto";
  $reason = "Auto";
  $silent = true;
} else {
  $name = get_name();
  $qa = get_qa();
  $reason = get_reason();
}

$f = false;
if($argv[2] == "-f") { $f = true; }

// change /etc/ssh/sshd_config   only on www6001  add this line -> LogLevel ERROR
echo "CrossChannel Pushcode\n";
echo "git update www6001-> /var/www/vhosts/mdotm.com\n\n";
$c = "ssh -q www6001 'sh /var/www/vhosts/mdotm.com/scripts/utils/git_for_mdotm.com.sh 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
echo "$c\n";
$output = array();
exec($c, $output);
print_r($output);  
echo "\n"; 

$smoketest = false;
if ($f == false) {
  $smoketest = smoketest();
}

if ($smoketest) {
 $today = date("F j, Y, g:i a T");
 $mail_subject = "CODE PUSH FAIL(" . $name . ") - $today";
 $mail_body = "PUSHCODE FAIL THE SMOKETEST:\n\n$smoketest\n\n";
 $mail_body .= "PUSHCODE FAIL at " . $today . " to " . $cluster . ".  Details below:\n\n";
 $mail_body .= "Pushed by: " . $name . "\n";
 $mail_body .= "QA by: " . $qa . "\n";
 $mail_body .= "Reason: " . $reason . "\n\n";
 echo $mail_body;
  
 $mail_return = crosschannel_mail("adops@crosschannel.com", "engineering@crosschannel.com", $mail_subject, $mail_body);
 if ($mail_return) echo("Message successfully sent!!\n");
 exit;
}

$servers[] = "www6002"; // add www6002   to update www6002
foreach ($servers as $server) {
  $h = "git reset --hard HEAD~1;";
  $c = "ssh -q $server 'cd /var/www/vhosts/mdotm.com && git fetch upstream && git merge upstream/master 2> /var/log/git.err  > /var/log/git.log' > /dev/null 2>&1 &";
  echo "$c\n";
  $output = array();
  exec($c, $output);  
  echo "\n";
}
for ($i=0; $i<3; $i++) {
  sleep(1);
  echo "[$i]";
}

$servers[] = "www6001"; // add www6001 to check if no git err  
echo "GITPULL server results recorded in servers table:\n";
foreach ($servers as $server) {
  $c = "ssh -q $server 'php /var/www/vhosts/mdotm.com/scripts/utils/gitpull' > /dev/null 2>&1 &";
  echo "$c\n";
  $output = array();
  exec($c, $output);  
}

$sql = "select hostname, gitpull_error from servers where length(gitpull_error) > 0";
if ( $res = mysql_query($sql) ) {
  while ( $a = mysql_fetch_object($res) ) {
    echo "{$a->hostname} - {$a->gitpull_error}\n";
  }
}
 
$today = date("F j, Y, g:i a T"); 
$mail_subject = "CODE PUSH mdotm.com (" . $name . ") - $today";
$mail_body = "Code was pushed at " . $today . " to " . $cluster . ".  Details below:\n\n";
$mail_body .= "Pushed by: " . $name . "\n";
$mail_body .= "QA by: " . $qa . "\n";
$mail_body .= "Reason: " . $reason . "\n\n";

$mail_return = crosschannel_mail("adops@crosschannel.com", "engineering@crosschannel.com", $mail_subject, $mail_body);
if ($mail_return) echo("Message successfully sent!!\n");
?>
