ssh wwwa0-12021428-hhp8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa0-12021428-ld93 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-08291210-sxb8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-5ng1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-9982 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-a1fd ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-b0yn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-dcsl ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-dnww ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-gr74 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-i3az ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-likc ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-nif2 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-tiby ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-tulr ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-adx-09080600-ugnu ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-rubicon-11031820-8l73 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-spotx-09081000-jzb0 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-spotx-09081000-sof7 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh wwwa1-spotx-09081000-yu0x ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www80-12011432-8t8h ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www80-12011432-vzrw ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-08291215-7dov ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-16mz ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-17is ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-1n0l ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-2fsn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-76s6 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-8rsi ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-b5ki ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-d6sc ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-df4l ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-dhr2 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-ga4e ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-h3gn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-j6mj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-jy7x ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-ky7m ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-mez7 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-pvh1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-ugsy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-vmtm ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-adx-09080600-x44k ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-amazon-09080600-h40i ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-amazon-09080600-uxkf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-fyber-09121200-pv20 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-rubicon-11031808-weuy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-2sf0 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-6eyd ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-ecay ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-iffx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-qv8s ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www81-spotx-09080600-s4aj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-cc2o ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-g9eh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-hrtw ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-k2kv ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-qbe4 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-rj4t ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-u3ci ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-uc8p ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-ybw8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-11222016-z4cv ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-2wsf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-6i0i ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-9akn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-bmk1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-d19d ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-ktxc ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-otvu ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-sdtr ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-sp65 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www60-12061656-tnt4 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6001 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6002 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6005 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6006 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6008 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6009 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www6010 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-46rf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-65ju ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-6ixq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-9shz ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-dbue ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-e028 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-i2on ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-iply ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-jxno ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-pymp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-08291230-wr81 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-013m ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-0s98 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-10oo ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-11io ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-1i42 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-1ncf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-1zsi ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-2aw9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-2qbn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-3cjl ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-3epv ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-3swf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-45qt ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-473n ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-49pz ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-4hej ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-4mej ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-4n42 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-4ykg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-5c7y ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-5jgh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-5sxv ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-5y5n ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-62ns ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-6f6x ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-6fle ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-6mjr ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-7kt8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-8bdq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-8d3l ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-8g1m ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-8j8g ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-8sfx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-983n ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-9tfk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-aa3t ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-asot ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ays6 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-b9dq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-bg67 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-bt0j ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-bun2 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-clm7 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-czwf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-dcx6 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-df6d ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-dg79 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-dsdn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-dt5q ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ewo1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-f3vu ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-f6an ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-fa2g ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-fm5i ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-frg8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ftpx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-g33z ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-goit ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-hf76 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-hio3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-hn5t ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-hurn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-hw0e ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-i2le ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-i650 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-iait ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-jdgt ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-jfpp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-jjky ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-jr6v ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-jv3q ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-k151 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-khas ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-khdj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-koqs ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-krtp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-kv57 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-l191 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-m4g9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-mfym ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-mjcw ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-mq4t ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-n3m3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-n8mk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-nsnk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-nzls ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-of6l ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ogh1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ohua ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ozln ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-p6jz ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-q105 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-qv5w ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-r7al ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-rwqp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-s0dp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-s7t9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tclp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tfhy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tlms ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tmlq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tmzd ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-tuyh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-um1g ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-v6md ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-v9cf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-veqh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-vlsq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-vpux ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-w3tg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-w5kh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-wh83 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-x97v ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-xfw8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-xkxt ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-y1mf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-y5hk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-yexo ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-ym25 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-z6fd ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-z9lg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-zaho ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-adx-11221651-zux7 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-fyber-08291236-1pir ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-fyber-08291236-bdq2 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-fyber-08291236-cum8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-007l ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-cc1j ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-iwou ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-k4ll ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-ovtf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www61-rubicon-11221909-py07 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www20-12011434-lhn3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www20-12011434-uq0o ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-amazon-11071055-7zoh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-amazon-11071055-9xp9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-amazon-11071055-ekze ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-auctionnotify-11291646-140z ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-01r2 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-0gnx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-0u38 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-12kl ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-1cxb ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-2ui5 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-4rys ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-5dp5 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-66s9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-6h35 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-6lfl ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-7976 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-7yt4 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-9ha5 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-d4b7 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-dci0 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-famf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-fdu3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-fiiy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-g013 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-g1v1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-gfth ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-hms8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-hqcj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-hqir ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-i05p ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-inhy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-jqhj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-k7i9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-khnk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-kobo ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-mb7m ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-o0nk ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-oqd1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-ps7s ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-qpmh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-r6hh ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-rg77 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-s37b ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-s3c8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-s4le ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-tk5k ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-us5e ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-uw6k ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-vjop ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-w3gq ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-wojl ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-wxr9 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-ygtn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-z0ar ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-z27d ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub-11281255-z4o5 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub2-11281813-0fk1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-mopub2-11281813-oy0e ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-opera-11291725-jgtr ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-opera-11291725-xv0r ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-1zbp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-57x3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-7i6i ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-9bhs ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-bzl3 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-cb1t ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-hg4f ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-kp1o ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-lfpf ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-m5cp ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-otft ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-qlbg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-rkd0 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-ru58 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-tarb ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-uc4v ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-x9it ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-rubicon-11041136-xzcy ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-1fhs ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-2btx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-7kzx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-94db ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-bwzs ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-coi5 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-e8uj ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-gugi ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-i0ix ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-k3b1 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-lsii ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-p65i ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-q42y ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-rv92 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-scqx ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-uwmu ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-wlmc ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-spotx-11071055-z1yo ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-5hy8 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-7svg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-9uft ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-ckpo ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-hhem ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-j4r0 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-joir ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-kavg ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-kfqm ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-ptjn ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-ueyb ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-wgp4 ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
ssh www21-yahoo-11071055-xm1g ps aux | egrep "/var/www/vhosts/crosschannel.com/bidder/bin/bt|/var/www/vhosts/crosschannel.com/bidder/bin/zn" 2>&1 &
