ssh -q ha6-m hostname -s && ssh -q ha6-m php -v
ssh -q ha6-sw-0a1l hostname -s && ssh -q ha6-sw-0a1l php -v
ssh -q ha6-sw-3gf5 hostname -s && ssh -q ha6-sw-3gf5 php -v
ssh -q ha6-sw-6xjq hostname -s && ssh -q ha6-sw-6xjq php -v
ssh -q ha6-sw-72ew hostname -s && ssh -q ha6-sw-72ew php -v
ssh -q ha6-sw-c5zz hostname -s && ssh -q ha6-sw-c5zz php -v
ssh -q ha6-sw-e8yu hostname -s && ssh -q ha6-sw-e8yu php -v
ssh -q ha6-sw-iamk hostname -s && ssh -q ha6-sw-iamk php -v
ssh -q ha6-sw-nujj hostname -s && ssh -q ha6-sw-nujj php -v
ssh -q ha6-sw-pzn0 hostname -s && ssh -q ha6-sw-pzn0 php -v
ssh -q ha6-sw-rrdq hostname -s && ssh -q ha6-sw-rrdq php -v
ssh -q ha6-w-0 hostname -s && ssh -q ha6-w-0 php -v
ssh -q ha6-w-1 hostname -s && ssh -q ha6-w-1 php -v
