ssh -q wwwa1-07hl hostname -s && ssh -q wwwa1-07hl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-3nt3 hostname -s && ssh -q wwwa1-3nt3 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-8kwb hostname -s && ssh -q wwwa1-8kwb cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-bjap hostname -s && ssh -q wwwa1-bjap cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-cqt1 hostname -s && ssh -q wwwa1-cqt1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-eh17 hostname -s && ssh -q wwwa1-eh17 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-eurd hostname -s && ssh -q wwwa1-eurd cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-gvqm hostname -s && ssh -q wwwa1-gvqm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-o9or hostname -s && ssh -q wwwa1-o9or cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-utbi hostname -s && ssh -q wwwa1-utbi cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q wwwa1-wadl hostname -s && ssh -q wwwa1-wadl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-0z19 hostname -s && ssh -q www81-0z19 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-1hme hostname -s && ssh -q www81-1hme cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-2bz9 hostname -s && ssh -q www81-2bz9 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-2hkl hostname -s && ssh -q www81-2hkl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-2jmo hostname -s && ssh -q www81-2jmo cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-2ngv hostname -s && ssh -q www81-2ngv cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-3i4v hostname -s && ssh -q www81-3i4v cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-3qvt hostname -s && ssh -q www81-3qvt cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-4ut8 hostname -s && ssh -q www81-4ut8 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-5z2q hostname -s && ssh -q www81-5z2q cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-6yyw hostname -s && ssh -q www81-6yyw cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-7khz hostname -s && ssh -q www81-7khz cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-9ojq hostname -s && ssh -q www81-9ojq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-9z2i hostname -s && ssh -q www81-9z2i cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-aqbx hostname -s && ssh -q www81-aqbx cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-avcj hostname -s && ssh -q www81-avcj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-avv7 hostname -s && ssh -q www81-avv7 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-b4us hostname -s && ssh -q www81-b4us cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-b9op hostname -s && ssh -q www81-b9op cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-c1j1 hostname -s && ssh -q www81-c1j1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-d0vc hostname -s && ssh -q www81-d0vc cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-fqkl hostname -s && ssh -q www81-fqkl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-gm6x hostname -s && ssh -q www81-gm6x cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-h10n hostname -s && ssh -q www81-h10n cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-hh5u hostname -s && ssh -q www81-hh5u cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-hwpn hostname -s && ssh -q www81-hwpn cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-i5i5 hostname -s && ssh -q www81-i5i5 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-is9f hostname -s && ssh -q www81-is9f cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-k45b hostname -s && ssh -q www81-k45b cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-kcpt hostname -s && ssh -q www81-kcpt cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-ktvt hostname -s && ssh -q www81-ktvt cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-kvl3 hostname -s && ssh -q www81-kvl3 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-l24y hostname -s && ssh -q www81-l24y cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-l5rc hostname -s && ssh -q www81-l5rc cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-lcqy hostname -s && ssh -q www81-lcqy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-lmen hostname -s && ssh -q www81-lmen cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-lmvb hostname -s && ssh -q www81-lmvb cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-m5ht hostname -s && ssh -q www81-m5ht cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-n5u9 hostname -s && ssh -q www81-n5u9 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-nk9w hostname -s && ssh -q www81-nk9w cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-no3r hostname -s && ssh -q www81-no3r cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-nscl hostname -s && ssh -q www81-nscl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-nva2 hostname -s && ssh -q www81-nva2 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-okw1 hostname -s && ssh -q www81-okw1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-peqy hostname -s && ssh -q www81-peqy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-s0zi hostname -s && ssh -q www81-s0zi cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-s9a1 hostname -s && ssh -q www81-s9a1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-tnsp hostname -s && ssh -q www81-tnsp cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-tvep hostname -s && ssh -q www81-tvep cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-u1wn hostname -s && ssh -q www81-u1wn cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-vnrt hostname -s && ssh -q www81-vnrt cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-w2en hostname -s && ssh -q www81-w2en cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-wvfr hostname -s && ssh -q www81-wvfr cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-xkx8 hostname -s && ssh -q www81-xkx8 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-xug0 hostname -s && ssh -q www81-xug0 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-yxmz hostname -s && ssh -q www81-yxmz cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-yxw6 hostname -s && ssh -q www81-yxw6 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-z5fp hostname -s && ssh -q www81-z5fp cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-zenz hostname -s && ssh -q www81-zenz cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www81-zk0u hostname -s && ssh -q www81-zk0u cat /proc/sys/net/ipv4/tcp_tw_reuse
