gcloud compute backend-services describe NAME
gcloud compute backend-services describe adx
gcloud compute backend-services describe adx-as
gcloud compute backend-services describe adx-eu
gcloud compute backend-services describe amazon
gcloud compute backend-services describe amazon-eu
gcloud compute backend-services describe auctionnotify
gcloud compute backend-services describe backend-as-p
gcloud compute backend-services describe backend-eu-p
gcloud compute backend-services describe backend-us-central-p
gcloud compute backend-services describe cdn
gcloud compute backend-services describe chatbot
gcloud compute backend-services describe click
gcloud compute backend-services describe fyber-falk
gcloud compute backend-services describe fyber-falk-eu
gcloud compute backend-services describe mdotmtv
gcloud compute backend-services describe mopub
gcloud compute backend-services describe mopub2
gcloud compute backend-services describe opera
gcloud compute backend-services describe platform
gcloud compute backend-services describe rubicon
gcloud compute backend-services describe rubicon-as
gcloud compute backend-services describe rubicon-eu
gcloud compute backend-services describe spotx
gcloud compute backend-services describe spotx-as
gcloud compute backend-services describe spotx-eu
gcloud compute backend-services describe spotx-global
gcloud compute backend-services describe www20-lb-1
gcloud compute backend-services describe www60
gcloud compute backend-services describe www80
gcloud compute backend-services describe wwwa0
gcloud compute backend-services describe yahoo
