ssh -q www6001 hostname -s && ssh -q www6001 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-0vvr hostname -s && ssh -q www61-0vvr cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-0wda hostname -s && ssh -q www61-0wda cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-10o5 hostname -s && ssh -q www61-10o5 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-12h3 hostname -s && ssh -q www61-12h3 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-1aty hostname -s && ssh -q www61-1aty cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-1cof hostname -s && ssh -q www61-1cof cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-2111 hostname -s && ssh -q www61-2111 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-2ni5 hostname -s && ssh -q www61-2ni5 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-3p27 hostname -s && ssh -q www61-3p27 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-3vjr hostname -s && ssh -q www61-3vjr cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-3yr1 hostname -s && ssh -q www61-3yr1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-3zg9 hostname -s && ssh -q www61-3zg9 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-41mm hostname -s && ssh -q www61-41mm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-4ne5 hostname -s && ssh -q www61-4ne5 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-4zvf hostname -s && ssh -q www61-4zvf cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-5gz0 hostname -s && ssh -q www61-5gz0 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-5udq hostname -s && ssh -q www61-5udq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-60zp hostname -s && ssh -q www61-60zp cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-6689 hostname -s && ssh -q www61-6689 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-6g8e hostname -s && ssh -q www61-6g8e cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-6lps hostname -s && ssh -q www61-6lps cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-6u4x hostname -s && ssh -q www61-6u4x cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-7bzh hostname -s && ssh -q www61-7bzh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-7clj hostname -s && ssh -q www61-7clj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-7iht hostname -s && ssh -q www61-7iht cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-7ncf hostname -s && ssh -q www61-7ncf cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-85fx hostname -s && ssh -q www61-85fx cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-8bg8 hostname -s && ssh -q www61-8bg8 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-8iwr hostname -s && ssh -q www61-8iwr cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-8wuy hostname -s && ssh -q www61-8wuy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-8xoz hostname -s && ssh -q www61-8xoz cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-9026 hostname -s && ssh -q www61-9026 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-91vk hostname -s && ssh -q www61-91vk cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-9op3 hostname -s && ssh -q www61-9op3 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-9rj4 hostname -s && ssh -q www61-9rj4 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-9wfg hostname -s && ssh -q www61-9wfg cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-a52w hostname -s && ssh -q www61-a52w cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-b1j0 hostname -s && ssh -q www61-b1j0 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-biyu hostname -s && ssh -q www61-biyu cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-bwob hostname -s && ssh -q www61-bwob cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-bxjh hostname -s && ssh -q www61-bxjh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-bzsq hostname -s && ssh -q www61-bzsq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-c8sw hostname -s && ssh -q www61-c8sw cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-cerh hostname -s && ssh -q www61-cerh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-dbcv hostname -s && ssh -q www61-dbcv cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-dxrm hostname -s && ssh -q www61-dxrm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-edx1 hostname -s && ssh -q www61-edx1 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-er4s hostname -s && ssh -q www61-er4s cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-evpz hostname -s && ssh -q www61-evpz cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-f7tk hostname -s && ssh -q www61-f7tk cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-fl2s hostname -s && ssh -q www61-fl2s cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-fzgh hostname -s && ssh -q www61-fzgh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-g2tm hostname -s && ssh -q www61-g2tm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-gbfm hostname -s && ssh -q www61-gbfm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-gkyh hostname -s && ssh -q www61-gkyh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-gm83 hostname -s && ssh -q www61-gm83 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-gtzy hostname -s && ssh -q www61-gtzy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-gwuv hostname -s && ssh -q www61-gwuv cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-hawx hostname -s && ssh -q www61-hawx cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-i0sc hostname -s && ssh -q www61-i0sc cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-i97d hostname -s && ssh -q www61-i97d cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-iiav hostname -s && ssh -q www61-iiav cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-imfh hostname -s && ssh -q www61-imfh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-itkd hostname -s && ssh -q www61-itkd cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-k91a hostname -s && ssh -q www61-k91a cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-knd8 hostname -s && ssh -q www61-knd8 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-l1um hostname -s && ssh -q www61-l1um cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-l46n hostname -s && ssh -q www61-l46n cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-l96r hostname -s && ssh -q www61-l96r cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-lbky hostname -s && ssh -q www61-lbky cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-le8x hostname -s && ssh -q www61-le8x cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-lec2 hostname -s && ssh -q www61-lec2 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-lri9 hostname -s && ssh -q www61-lri9 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-lsq4 hostname -s && ssh -q www61-lsq4 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-m85m hostname -s && ssh -q www61-m85m cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-m8m3 hostname -s && ssh -q www61-m8m3 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-mey6 hostname -s && ssh -q www61-mey6 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-mly4 hostname -s && ssh -q www61-mly4 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-nk7f hostname -s && ssh -q www61-nk7f cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-npdb hostname -s && ssh -q www61-npdb cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-nuec hostname -s && ssh -q www61-nuec cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-nvce hostname -s && ssh -q www61-nvce cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-oa6z hostname -s && ssh -q www61-oa6z cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-opfu hostname -s && ssh -q www61-opfu cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-oqas hostname -s && ssh -q www61-oqas cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-owjj hostname -s && ssh -q www61-owjj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-p77m hostname -s && ssh -q www61-p77m cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-plxl hostname -s && ssh -q www61-plxl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-ps1m hostname -s && ssh -q www61-ps1m cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-puzk hostname -s && ssh -q www61-puzk cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-q2eq hostname -s && ssh -q www61-q2eq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-q3ij hostname -s && ssh -q www61-q3ij cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-qmwa hostname -s && ssh -q www61-qmwa cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-qras hostname -s && ssh -q www61-qras cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-r3dy hostname -s && ssh -q www61-r3dy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-rstj hostname -s && ssh -q www61-rstj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-rwhh hostname -s && ssh -q www61-rwhh cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-s5jm hostname -s && ssh -q www61-s5jm cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-s9ng hostname -s && ssh -q www61-s9ng cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-seti hostname -s && ssh -q www61-seti cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-sqt0 hostname -s && ssh -q www61-sqt0 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-t15i hostname -s && ssh -q www61-t15i cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-t4gy hostname -s && ssh -q www61-t4gy cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-t56k hostname -s && ssh -q www61-t56k cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-t9mg hostname -s && ssh -q www61-t9mg cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-tacd hostname -s && ssh -q www61-tacd cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-tcfa hostname -s && ssh -q www61-tcfa cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-tjbe hostname -s && ssh -q www61-tjbe cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-tw0b hostname -s && ssh -q www61-tw0b cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-u2km hostname -s && ssh -q www61-u2km cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-u38s hostname -s && ssh -q www61-u38s cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-u93n hostname -s && ssh -q www61-u93n cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-u9bb hostname -s && ssh -q www61-u9bb cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-une7 hostname -s && ssh -q www61-une7 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-v777 hostname -s && ssh -q www61-v777 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-vpdj hostname -s && ssh -q www61-vpdj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-w77r hostname -s && ssh -q www61-w77r cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-wcfl hostname -s && ssh -q www61-wcfl cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-wknq hostname -s && ssh -q www61-wknq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-wsew hostname -s && ssh -q www61-wsew cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-wv10 hostname -s && ssh -q www61-wv10 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-xhab hostname -s && ssh -q www61-xhab cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-y1ca hostname -s && ssh -q www61-y1ca cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-y4ay hostname -s && ssh -q www61-y4ay cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-y8ea hostname -s && ssh -q www61-y8ea cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-yg3f hostname -s && ssh -q www61-yg3f cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-ygaj hostname -s && ssh -q www61-ygaj cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-ymej hostname -s && ssh -q www61-ymej cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-z65h hostname -s && ssh -q www61-z65h cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-zbi0 hostname -s && ssh -q www61-zbi0 cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-zkbq hostname -s && ssh -q www61-zkbq cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-zksd hostname -s && ssh -q www61-zksd cat /proc/sys/net/ipv4/tcp_tw_reuse
ssh -q www61-zwrd hostname -s && ssh -q www61-zwrd cat /proc/sys/net/ipv4/tcp_tw_reuse
