ssh -q www60-52wv hostname -s && ssh -q www60-52wv php -m | grep lua
ssh -q www60-6wxg hostname -s && ssh -q www60-6wxg php -m | grep lua
ssh -q www60-a5ej hostname -s && ssh -q www60-a5ej php -m | grep lua
ssh -q www60-as8g hostname -s && ssh -q www60-as8g php -m | grep lua
ssh -q www60-b2cf hostname -s && ssh -q www60-b2cf php -m | grep lua
ssh -q www60-f016 hostname -s && ssh -q www60-f016 php -m | grep lua
ssh -q www60-h3ur hostname -s && ssh -q www60-h3ur php -m | grep lua
ssh -q www60-j8px hostname -s && ssh -q www60-j8px php -m | grep lua
ssh -q www60-l5hm hostname -s && ssh -q www60-l5hm php -m | grep lua
ssh -q www60-mb3i hostname -s && ssh -q www60-mb3i php -m | grep lua
ssh -q www60-pkpt hostname -s && ssh -q www60-pkpt php -m | grep lua
ssh -q www60-x9cb hostname -s && ssh -q www60-x9cb php -m | grep lua
ssh -q www60-zi7i hostname -s && ssh -q www60-zi7i php -m | grep lua
ssh -q www60-zr67 hostname -s && ssh -q www60-zr67 php -m | grep lua
ssh -q www6001 hostname -s && ssh -q www6001 php -m | grep lua
