ssh ha6-fat-m sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-2brg sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-kvxm sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-skjz sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-v1kb sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-xl45 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-sw-z283 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-w-0 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-fat-w-1 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-m sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-320t sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-34pk sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-4pq4 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-52qk sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-52r3 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-5dm2 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-62sx sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-6ctq sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-73vt sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-9sm9 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-dptm sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-frv5 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-fznf sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-gcv6 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-mxvp sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-pfn3 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-qnkl sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-sc9s sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-tbj7 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-sw-xk9w sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-w-0 sh /root/scripts/bt_restart.sh 2>&1 &
ssh ha6-w-1 sh /root/scripts/bt_restart.sh 2>&1 &
