ssh -q wwwa0-dj2w sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa0-ljg1 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa0-vwrc sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-3lhm sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-5udy sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-ed39 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-ehy9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-f6uf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-grtl sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-gshu sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-ifnt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-jog8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q wwwa2-qhdw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www80-86d7 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www80-fmkj sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-0690 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-1526 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-1km8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-1rzh sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-1yvp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-22x8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-2d0l sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-2v1o sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-2yb8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-3bf7 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-3fdz sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-3tpt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-46gn sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-47vi sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-4cq6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-4hqv sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-509x sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-5z0d sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-694z sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-6xn5 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-77li sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-8f42 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-8k7w sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-9t34 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-9uu5 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-aklo sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-an2g sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-bbug sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-bwwp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-cioh sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-dd8c sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-dx27 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-e1co sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-egep sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-gh5m sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-hjw3 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-hwaw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-imi6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-j181 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-j744 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-jn4b sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-jt50 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-jtwy sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-k8wk sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-km1l sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-l65q sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-llc6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-mj2j sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-mn80 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-mo99 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-rcbc sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-s4fw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-tytu sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-tzf8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-u1jq sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-uc63 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-up9u sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-v8d0 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-vvsw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-wbn1 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-wff5 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-xgpi sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-y2n9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-y8l6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-yb55 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-yjs2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-yui3 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-z9o4 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-zjgs sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-zws8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www81-zxba sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-05m2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-1kf4 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-2w9t sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-41td sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-5pze sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-5upo sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-8374 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-8dbw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-94ac sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-br5o sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-de4y sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-dov5 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-f8bf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-laqm sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-n71s sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-qwrj sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-rc0j sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www60-zcib sh /root/scripts/fluentd_remove.sh 2>&1 &
#ssh -q www6001 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-07w2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-09mr sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-0gfe sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-0rvi sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-0z3c sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-12u9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-16ia sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-17v8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1eef sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1g6v sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1kgf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1ri8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1u5c sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-1w5q sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-20qb sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-243p sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-2equ sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-2vfl sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-2vv8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-30s9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-32bp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-3egh sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-3mei sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-3q2m sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-40sl sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-47ae sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-4gyg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-4h14 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-4jmg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-4u0e sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-4ytp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5735 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5e3l sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5f07 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5fr9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5kf2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5kth sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5oax sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5trx sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5zia sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-5zw0 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6088 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6bx4 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6drp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6i01 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6m26 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6rmv sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-6zjp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-71ot sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7euf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7fbz sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7nzt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7our sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7wx3 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-7y7x sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-818q sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-897t sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8cr2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8dqt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8gyg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8jtf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8o60 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8oyc sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8utx sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8yju sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-8zyu sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-9445 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-a1bd sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-a4ko sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-atcm sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-axnp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ayql sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ba0v sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-byyd sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-cbuf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-cr10 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-dhog sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-dics sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-dq90 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-dtbu sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-e95o sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-e989 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-en4b sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-epkf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-f3f2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-f51w sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-f5hu sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-f7ss sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-fos2 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-g41u sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-g9wv sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-gpbd sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-gy2v sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-h4bp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hdv9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hdwb sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hgt1 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hmyq sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hnkc sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-hrdb sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-if40 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-iih0 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ijfx sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-is8q sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-iu8u sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ivol sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-iwww sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-iz6z sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-jfxa sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-k52d sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-k7jc sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-k8kn sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kdo6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kj1c sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kkfo sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kvzf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kxxk sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-kz7s sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-l1ap sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-l5el sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-lj7j sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-llf7 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ltn4 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ltxr sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-lu8i sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-m6ka sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-mo9r sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-mrbt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-mxrp sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-mxz9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-neyf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-nytg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-odmk sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ok70 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-orcj sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-pfm7 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-pl39 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-poiz sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-prj8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-pzda sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-q6xf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-qm9d sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-quwd sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-qv8j sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-qy9l sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-qz90 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ri3o sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-rjbs sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-rmo4 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-rmrr sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ro4m sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-s6h9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-sci5 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-snjv sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-sqbw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-st56 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-suba sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-tahf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-tlvx sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-tmh9 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-tpmw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ubzn sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ueos sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ugzt sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-uqjo sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ux20 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-uxbn sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-uywb sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-v0sw sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-vm1j sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-vmuy sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-vo01 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-vofg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-w4lh sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-wd52 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-wsby sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-wwf6 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-x2wr sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-x6ga sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-x7yf sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-xcc7 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-xf0t sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-xfj0 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-xmor sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-xpcd sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-y0p8 sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-y8xl sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-yd5l sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-yi5u sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ylft sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-ynvg sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-z1ky sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-z5oq sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-z6zx sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-z79i sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-zdkr sh /root/scripts/fluentd_remove.sh 2>&1 &
ssh -q www61-zsuw sh /root/scripts/fluentd_remove.sh 2>&1 &
