gsutil du -s gs://cc_bk
gsutil du -s gs://cc_addressable
gsutil du -s gs://cc_mz
gsutil du -s gs://cc_seg
gsutil du -s gs://crosscannel_spark
gsutil du -s gs://crosschannel_segments
gsutil du -s gs://crosschannel_tvfiles
gsutil du -s gs://crosschannel_spark
gsutil du -s gs://cc_assists
gsutil du -s gs://cc_buckets_as
gsutil du -s gs://cc_buckets_eu
gsutil du -s gs://cc_buckets_us
gsutil du -s gs://cc_campaign
gsutil du -s gs://cc_cold
gsutil du -s gs://cc_conversion
gsutil du -s gs://cc_crosswise
gsutil du -s gs://cc_fyi
gsutil du -s gs://cc_log
gsutil du -s gs://cc_pico
gsutil du -s gs://cc_reach
gsutil du -s gs://cc_rentrak
gsutil du -s gs://cc_tapad
gsutil du -s gs://cc_track
gsutil du -s gs://cc_tv
gsutil du -s gs://cc_video
gsutil du -s gs://crosschannel-sample
gsutil du -s gs://crosschannel_bid
gsutil du -s gs://crosschannel_billing
gsutil du -s gs://crosschannel_cdn
gsutil du -s gs://crosschannel_clients
gsutil du -s gs://crosschannel_conversion
gsutil du -s gs://crosschannel_dev
gsutil du -s gs://crosschannel_fyi
gsutil du -s gs://crosschannel_hadoop
gsutil du -s gs://crosschannel_infogroup
gsutil du -s gs://crosschannel_inventorylog
gsutil du -s gs://crosschannel_log
gsutil du -s gs://crosschannel_probe
gsutil du -s gs://crosschannel_profile
gsutil du -s gs://crosschannel_rentrak
gsutil du -s gs://crosschannel_rtf
gsutil du -s gs://crosschannel_sitelogdetail
gsutil du -s gs://crosschannel_tps
gsutil du -s gs://crosschannel_track
gsutil du -s gs://dataproc-c0ea2ea0-5783-466c-9b2e-127978b53680-us
gsutil du -s gs://shutdown_scripts
gsutil du -s gs://startup_scripts_us
