#rsync -avz /etc/profile.d/ log6b:/etc/profile.d/
#rsync -avz /etc/profile.d/ log00:/etc/profile.d/
rsync -avz /etc/profile.d/ log6:/etc/profile.d/
rsync -avz /etc/profile.d/ log6c:/etc/profile.d/
rsync -avz /etc/profile.d/ www6001:/etc/profile.d/
rsync -avz /etc/profile.d/ www6002:/etc/profile.d/
rsync -avz /etc/profile.d/ www6005:/etc/profile.d/
rsync -avz /etc/profile.d/ www6006:/etc/profile.d/
rsync -avz /etc/profile.d/ www6008:/etc/profile.d/
rsync -avz /etc/profile.d/ www6009:/etc/profile.d/
rsync -avz /etc/profile.d/ www6010:/etc/profile.d/
