scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-m:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-2brg:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-kvxm:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-skjz:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-v1kb:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-xl45:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-sw-z283:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-w-0:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-fat-w-1:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-m:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-320t:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-34pk:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-4pq4:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-52qk:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-52r3:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-5dm2:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-62sx:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-6ctq:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-73vt:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-9sm9:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-dptm:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-frv5:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-fznf:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-gcv6:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-mxvp:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-pfn3:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-qnkl:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-sc9s:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-tbj7:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-sw-xk9w:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-w-0:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
scp /var/www/vhosts/crosschannel.com/bidder/bin/* ha6-w-1:/var/www/vhosts/crosschannel.com/bidder/bin/ 2>&1 &
