scp /root/scripts/bt_restart.sh ha6-fat-m:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-2brg:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-kvxm:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-skjz:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-v1kb:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-xl45:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-sw-z283:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-w-0:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-fat-w-1:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-m:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-320t:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-34pk:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-4pq4:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-52qk:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-52r3:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-5dm2:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-62sx:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-6ctq:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-73vt:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-9sm9:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-dptm:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-frv5:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-fznf:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-gcv6:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-mxvp:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-pfn3:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-qnkl:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-sc9s:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-tbj7:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-sw-xk9w:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-w-0:/root/scripts/ 2>&1 &
scp /root/scripts/bt_restart.sh ha6-w-1:/root/scripts/ 2>&1 &
