scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg ars-swarm-20171006-3xf1:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg ars-swarm-20171006-9gwx:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg ars-swarm-20171006-k8pw:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg bruce-swarm-10031720-kt6w:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg demo-swarm-wolk-com-80kh:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg swarm-mayumi-08181200-0tw5:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg swarm-mayumi-08181200-qb3x:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg swarm-michael-10031740-3f69:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg swarm-michael-10031740-f42r:/etc/nagios/ 2>&1 &
scp /var/www/vhosts/anand/mdotm.com/httpdocs/gce/nagios/nrpe.cfg swarm-michael-10031740-j34p:/etc/nagios/ 2>&1 &
