scp /usr/lib64/nagios/plugins/check_bq.sh log6b:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh api-colorfulnotion-com-3t4c:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh factual-g8mj:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh log00:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh log6:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh log6c:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6001:/usr/lib64/nagios/plugins/
#scp /usr/lib64/nagios/plugins/check_bq.sh www6002:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6005:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6006:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6008:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6009:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www6010:/usr/lib64/nagios/plugins/
scp /usr/lib64/nagios/plugins/check_bq.sh www69-a-colorfulthought-co-nl43:/usr/lib64/nagios/plugins/
