scp /root/scripts/hbasechk.sh wwwa1-3nt3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-eh17:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-eurd:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-f9wf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-k8zp:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-l2bf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-qeel:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-s178:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-t6h8:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-v214:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-vsht:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh wwwa1-w5wf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-0z19:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-1hme:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-2hkl:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-5fj2:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-5sxj:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-6yyw:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-7khz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-7zah:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-945o:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-9ojq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-aqbx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-avv7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-b4us:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-bq9l:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-c1j1:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-ejbv:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-gm6x:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-h4rj:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-hh5u:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-i5i5:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-is9f:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-jl6q:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-k10d:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-ktvt:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-l24y:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-lcqy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-lmvb:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-lwbx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-m5ht:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-m5iv:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-n5u9:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-nh8q:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-nk9w:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-no3r:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-nscl:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-nva2:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-okw1:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-peqy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-tnsp:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-tow3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-u1wn:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-w2en:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-wf7a:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-wi2a:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-xkx8:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-yxmz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-zenz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www81-zk0u:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www6001:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-03sd:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-0big:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-0i0v:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-10o5:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-10v2:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-12h3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-18dh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-1cof:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-1nhw:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-20a7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-2hh5:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-2xtb:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-371e:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-3bfz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-3p27:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-3ye7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-3yr1:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-41mm:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-42cy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-4czq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-4ne5:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-4x60:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-4zvf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-574u:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-5af1:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-5bip:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-5gz0:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-5udq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-5yyr:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-60zp:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-6689:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-68zw:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-6g8e:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-6iu0:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-6mht:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-6u4x:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7bzh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7clj:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7iht:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7js6:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7kek:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-7ncf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-82yb:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-85fx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-889e:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-8wuy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9026:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9op3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9q98:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9rj4:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9rwz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9taw:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9wfg:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-9y6i:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-a136:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-a1b7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-axmd:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-b1j0:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-b61r:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-bb1v:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-bwob:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-bxjh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-bzsq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-c8sw:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-cejx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-cerh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-chn5:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-cm19:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-d45m:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-e58m:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-e7wd:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-evpz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ew80:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-fl2s:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-fzgh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-g0cu:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-gbfm:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ggy2:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-gkyh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-gm83:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-gtzy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-h5mc:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-hawx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-hj0h:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-i97d:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-idgk:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-iiav:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-imfh:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-j2js:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-k4ew:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-k91a:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-k9z3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-l46n:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lbky:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lec2:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lm99:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lrdi:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lri9:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lsq4:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-lukj:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-m9r3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-mly4:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-mz85:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-nkbv:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-nvce:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-oa6z:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-opfu:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-oqas:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-oshy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ozjx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-p77m:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-pgox:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ps1m:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-q2eq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-q3ij:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-q4mz:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-q992:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-qjr1:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-qmwa:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-qras:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-qxei:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-r5ry:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-rlwt:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-s9ng:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-seti:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-sqt0:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-t15i:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-t4gy:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-t56k:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-to9l:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-tw0b:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-u2km:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-u38s:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-u93n:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ugcf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-une7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-vi3v:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-vls0:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-wknq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-wsew:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-wv10:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-xhab:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-xlqp:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-xmro:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-xsgx:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-xvzp:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-y03o:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-y1ca:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-y4ay:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-y562:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-y8ea:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ygaj:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ylg7:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-ymej:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-yu43:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-z0w3:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-z65h:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-zcwf:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-zkbq:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-zksd:/root/scripts/ 2>&1 &
scp /root/scripts/hbasechk.sh www61-zmux:/root/scripts/ 2>&1 &
