scp /root/scripts/fluentd_remove.sh wwwa0-dj2w:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa0-ljg1:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa0-vwrc:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-3lhm:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-5udy:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-ed39:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-ehy9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-f6uf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-grtl:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-gshu:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-ifnt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-jog8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh wwwa2-qhdw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www80-86d7:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www80-fmkj:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-0690:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-1526:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-1km8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-1rzh:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-1yvp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-22x8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-2d0l:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-2v1o:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-2yb8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-3bf7:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-3fdz:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-3tpt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-46gn:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-47vi:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-4cq6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-4hqv:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-4uda:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-509x:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-5z0d:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-694z:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-6xn5:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-77li:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-8f42:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-8k7w:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-9t34:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-9uu5:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-aklo:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-an2g:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-bbug:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-bwwp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-cioh:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-dd8c:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-dx27:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-e1co:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-egep:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-gh5m:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-hjw3:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-hwaw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-imi6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-j181:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-j744:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-jn4b:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-jt50:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-jtwy:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-k8wk:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-km1l:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-l65q:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-llc6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-mj2j:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-mn80:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-mo99:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-rcbc:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-s4fw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-s60a:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-tytu:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-tzf8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-u1jq:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-uc63:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-up9u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-v8d0:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-vvsw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-wbn1:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-wff5:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-xgpi:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-y2n9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-y8l6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-yb55:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-yjs2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-yui3:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-z9o4:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-zjgs:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-zws8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www81-zxba:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-05m2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-1kf4:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-2w9t:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-41td:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-5pze:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-5upo:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-8374:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-8dbw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-94ac:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-br5o:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-de4y:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-dov5:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-f8bf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-laqm:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-n71s:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-qwrj:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-rc0j:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www60-zcib:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-07w2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-09mr:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-0gfe:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-0rvi:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-0z3c:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-12u9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-16ia:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-17v8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1eef:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1g6v:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1kgf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1ri8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1u5c:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-1w5q:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-20qb:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-243p:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-2equ:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-2vfl:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-2vv8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-30s9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-32bp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-3egh:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-3mei:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-3q2m:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-40sl:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-47ae:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-4gyg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-4h14:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-4jmg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-4u0e:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-4ytp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5735:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5e3l:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5f07:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5fr9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5kf2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5kth:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5oax:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5trx:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5zia:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-5zw0:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6088:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6bx4:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6drp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6i01:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6m26:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6rmv:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-6zjp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-71ot:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7euf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7fbz:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7lnm:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7nzt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7our:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7wx3:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-7y7x:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-818q:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-897t:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8cr2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8dqt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8gyg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8jtf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8o60:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8oyc:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8utx:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8yju:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-8zyu:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-9445:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-a1bd:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-a4ko:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-atcm:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-axnp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ayql:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ba0v:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-byyd:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-cbuf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-cr10:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-dhog:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-dics:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-dq90:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-dtbu:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-e95o:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-e989:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-en4b:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-epkf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-f3f2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-f51w:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-f5hu:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-f7ss:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-fos2:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-g41u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-g9wv:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-gpbd:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-gy2v:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-h4bp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hdv9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hdwb:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hgt1:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hmyq:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hnkc:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-hrdb:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-if40:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-iih0:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ijfx:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-is8q:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-iu8u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ivol:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-iwww:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-iz6z:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-jfxa:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-k52d:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-k7jc:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-k8kn:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kdo6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kj1c:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kkfo:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kvzf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kxxk:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-kz7s:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-l1ap:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-l5el:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-lj7j:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-llf7:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ltn4:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ltxr:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-lu8i:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-m6ka:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-mo9r:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-mrbt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-mxrp:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-mxz9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-neyf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-nytg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-odmk:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ok70:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-op6u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-orcj:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-pfm7:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-pl39:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-poiz:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-prj8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-pzda:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-q6xf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-qm9d:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-quwd:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-qv8j:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-qy9l:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-qz90:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-rgqm:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ri3o:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-rjbs:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-rmo4:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-rmrr:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ro4m:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-s6h9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-sci5:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-snjv:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-sqbw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-st56:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-suba:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-tahf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-tlvx:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-tmh9:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-tpmw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ubzn:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ueos:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ugzt:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-uqjo:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ux20:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-uxbn:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-uywb:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-v0sw:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-vd4u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-vm1j:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-vmuy:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-vo01:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-vofg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-w4lh:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-wd52:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-wsby:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-wwf6:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-x2wr:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-x6ga:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-x7yf:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-xcc7:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-xf0t:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-xfj0:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-xmor:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-xpcd:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-y0p8:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-y8xl:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-yd5l:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-yi5u:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ylft:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-ynvg:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-z1ky:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-z5oq:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-z6zx:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-z79i:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-zdkr:/root/scripts/ 2>&1 &
scp /root/scripts/fluentd_remove.sh www61-zsuw:/root/scripts/ 2>&1 &
