scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-m:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-l7p6:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-ndlg:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-sflh:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-vvqg:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-wl3p:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-sw-zc4t:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-w-0:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-fat-w-1:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-m:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-08ml:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-1c3x:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-4d4w:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-644b:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-7rnj:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-8njg:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-bvl2:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-bxwk:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-dn74:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-fzvj:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-jdnx:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-kkqs:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-l53f:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-l8b1:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-mrjs:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-rmvh:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-t6fr:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-vc6z:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-wghz:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-sw-xd67:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-w-0:/usr/lib/nagios/plugins/ 2>&1 &
scp /usr/lib64/nagios/plugins/check_syslog-ng.sh ha6-w-1:/usr/lib/nagios/plugins/ 2>&1 &
