#mkdir -p /var/www/vhosts/sourabh && cd /var/www/vhosts/sourabh && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/mayumi && cd /var/www/vhosts/mayumi && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/huisi && cd /var/www/vhosts/huisi && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/alina && cd /var/www/vhosts/alina && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/yvan && cd /var/www/vhosts/yvan && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/rodney && cd /var/www/vhosts/rodney && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/yaron && cd /var/www/vhosts/yaron && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
#mkdir -p /var/www/vhosts/anand && cd /var/www/vhosts/anand && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
mkdir -p /var/www/vhosts/bruce && cd /var/www/vhosts/bruce && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
mkdir -p /var/www/vhosts/michael && cd /var/www/vhosts/michael && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
mkdir -p /var/www/vhosts/adops && cd /var/www/vhosts/adops && git clone git@github.com:sourabhniyogi/mdotm.com.git 2>&1 &
