apiVersion: v1
kind: Pod
metadata:
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    name: busybox1
    args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
  - image: busybox
    name: busybox2
    args:
    - /bin/sh
    - -c
    - echo hello; sleep 3600
