apiVersion: v1
kind: Pod
metadata:
        name: busybox
        labels:
                run: busybox
spec:
        containers:
                - image: busybox
                  name: busybox
                  command: ["env"]

