apiVersion: batch/v1beta1
kind: CronJob
metadata:
  creationTimestamp: null
  name: cronjob1
spec:
  jobTemplate:
    metadata:
      creationTimestamp: null
      name: cronjob1
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            - date; echo Hello from the Kubernetes cluster
            image: busybox
            name: cronjob1
            resources: {}
          restartPolicy: OnFailure
  schedule: '*/1 * * * *'
status: {}
