apiVersion: v1
kind: Pod
metadata:
        name: nginx
        namespace: mynamespace
        labels:
                run: nginx
spec:
        containers:
                - image: nginx
                  name: nginx

