# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
#alias vi='/usr/bin/vim'
alias plasmastart='vi /usr/local/swarmdb/scripts/plasma-start.sh'
alias adminpeers='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec admin.peers'
alias remoteAddress='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec admin.peers | grep remoteAddress'
alias peercount='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec net.peerCount'
alias nodeinfo='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec admin.nodeInfo'
alias blocknumber='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec eth.blockNumber'
alias eth.getbalance='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw attach /root/data/plasmachain.ipc --exec eth.getBalance\(eth.coinbase\)'
alias plasma.account='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw --datadir /root/data account list 2> /dev/null | awk "{print$3}" | cut -d "{" -f2 | cut -d "}" -f1'
alias plasmainit='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw --datadir /root/data init /root/data/genesis.json'
alias removedb='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw removedb --datadir /root/data'
alias plasma.attach='/root/go/src/github.com/wolkdb/plasma/build/bin/plasma attach /root/data/plasmachain.ipc'
alias bashrc='vi ~/.bashrc'
alias sourcebashrc='source ~/.bashrc'
alias watch='watch '

if [ -f /usr/sbin/ifconfig ]; then
eth=`ifconfig eth0 | grep inet | awk '{print$2}'`
fi

acct=`/root/go/src/github.com/wolkdb/plasma/build/bin/plasma-gw --datadir /root/data account list 2> /dev/null | awk '{print$3}' | cut -d "{" -f2 | cut -d "}" -f1`

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=/root/sbin:/root/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH=$PATH:/root/go/bin
export PATH=$PATH:/root/go/src/github.com/wolkdb/plasma/build/bin

if [ -d /root/data ]; then
export DATADIR=/root/data
fi

#if [ -d /root/data ]; then
#cd /root/data
#fi

# google auth credentials for datastore access
export GOOGLE_APPLICATION_CREDENTIALS="/root/.google/crosschannel-1307-520dd999e93e.json"

set -o ignoreeof
