apiVersion: apps/v1
kind: Deployment
metadata:
  name: mini
  labels:
    app: mini
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mini
  template:
    metadata:
      labels:
        app: mini
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: k7-2
        image: gcr.io/us-west1-wlk/wolkinc/mini:201908142026
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 2087
          name: k7-2
        - containerPort: 32007
          name: k7-2-p2p
        securityContext:
          privileged: true
      hostNetwork: true
