# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='/usr/bin/vim'

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

export PATH=$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vhosts/mdotm.com/scripts/utils:/usr/local/share/google/google-cloud-sdk:/usr/local/share/google/google-cloud-sdk/bin:/usr/local/go/bin:/var/www/vhosts/crosschannel.com/go/bin/
export GOPATH=/var/www/vhosts/crosschannel.com/go:/var/www/vhosts/crosschannel.com/bidder
export GOROOT=/usr/local/go
export JAVA_HOME=/usr/lib/jvm/jre-1.8.0-openjdk.x86_64/
