# USED FOR docker image wolkinc/algorand
FROM ubuntu:18.04
ENV GOLANG_VERSION 1.12
ENV DEBIAN_FRONTEND noninteractive

RUN ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

RUN mkdir /root/.ssh
COPY ssh/id_rsa /root/.ssh/id_rsa
COPY ssh/id_rsa.pub /root/.ssh/id_rsa.pub
COPY ssh/authorized_keys /root/.ssh/authorized_keys
RUN mkdir /root/scripts
COPY algod-check.sh /root/scripts/
COPY algod-start.sh /root/scripts/
COPY cron-start.sh /root/scripts/
COPY git-update.sh /root/scripts/
RUN mkdir /root/wolkdev
RUN apt update && apt-get install -y git apt-utils libboost-all-dev wget sqlite3 autoconf sudo tzdata bsdmainutils vim cron mlocate curl apt-transport-https ca-certificates
RUN apt-get -y upgrade

# gcloud/gsutil install
COPY google-cloud-sdk.list /etc/apt/sources.list.d/google-cloud-sdk.list
RUN wget https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg
RUN apt-key add /usr/share/keyrings/cloud.google.gpg
RUN apt update && apt-get install -y google-cloud-sdk

RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
RUN echo "UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config
COPY .bashrc /root/

COPY crontab /var/spool/cron/crontabs/root

WORKDIR /root
RUN wget --quiet https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz && tar -xvf go${GOLANG_VERSION}.linux-amd64.tar.gz && mv go /usr/local
RUN mkdir -p /root/go/bin
ENV GOROOT /usr/local/go
ENV GOPATH /root/go
ENV GOBIN /root/go/bin
ENV PATH   $GOPATH/bin:$GOROOT/bin:$PATH
RUN mkdir -p $GOPATH/src/github.com/algorand
WORKDIR $GOPATH/src/github.com/algorand
RUN git clone git@github.com:wolkdb/go-algorand.git
WORKDIR /root
ENTRYPOINT "/root/scripts/algod-start.sh" ; "/root/scripts/cron-start.sh" ; "/bin/bash"
CMD []
