# .bashrc

# User specific aliases and functions

alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias vi='/usr/bin/vim'

alias bashrc='vi ~/.bashrc'
alias sourcebashrc='source ~/.bashrc'
alias watch='watch '

if [ -f /usr/sbin/ifconfig ]; then
eth=`ifconfig eth0 | grep inet | awk '{print$2}'`
fi

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

export PATH=/root/sbin:/root/bin:/usr/sbin:/usr/bin:/sbin:/bin
export PATH=$PATH:/root/go/bin
export PATH=$PATH:/root/go/src/github.com/wolkdb/plasma/build/bin
export PATH=$PATH:/root/sql/bin

if [ -d /root/data ]; then
export DATADIR=/root/sql/qdata
fi

if [ -d /root/sql/qdata ]; then
cd /root/sql/qdata 
fi

# google auth credentials for datastore access
export GOOGLE_APPLICATION_CREDENTIALS="/root/.google/crosschannel-1307-520dd999e93e.json"

set -o ignoreeof
