cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ap-south-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-eu-west-3.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-eu-north-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-eu-west-2.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-eu-west-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ap-northeast-2.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ap-northeast-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-sa-east-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ca-central-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ap-southeast-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-ap-southeast-2.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-eu-central-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-us-east-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-us-east-2.sh
#cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-us-west-1.sh
cp startup-script-cloudstore-repo-aws.sh startup-script-cloudstore-repo-aws-us-west-2.sh
