FROM ubuntu:18.04
ENV GOLANG_VERSION 1.12
ENV DEBIAN_FRONTEND noninteractive

RUN ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

RUN mkdir /root/.ssh
COPY ssh/id_rsa /root/.ssh/id_rsa
COPY ssh/id_rsa.pub /root/.ssh/id_rsa.pub
RUN mkdir /root/scripts
COPY algod-start.sh /root/scripts/
COPY git-update.sh /root/scripts/
RUN mkdir /root/wolkdev
RUN apt update && apt-get install -y git libboost-all-dev wget sqlite3 autoconf sudo tzdata bsdmainutils vim cron mlocate
RUN echo "StrictHostKeyChecking no" >> /etc/ssh/ssh_config
RUN echo "UserKnownHostsFile /dev/null" >> /etc/ssh/ssh_config
RUN echo "Host *" >> /etc/ssh/ssh_config
COPY .bashrc /root/

COPY crontab /var/spool/cron/crontabs/root

WORKDIR /root
RUN wget --quiet https://dl.google.com/go/go${GOLANG_VERSION}.linux-amd64.tar.gz && tar -xvf go${GOLANG_VERSION}.linux-amd64.tar.gz && mv go /usr/local
RUN mkdir -p /root/go/bin
ENV GOROOT /usr/local/go
ENV GOPATH /root/go
ENV GOBIN /root/go/bin
ENV PATH   $GOPATH/bin:$GOROOT/bin:$PATH
RUN mkdir -p $GOPATH/src/github.com/algorand
ENTRYPOINT ["/bin/bash"]
CMD []
