[
{"hostname":"wolk-0-gc-us-west1-datastore","dns":"c0","project":"us-west1-wlk","datacenter":"us-west1-a","publicip":"34.83.254.22","cloudprovider":"gc","consensus":true,"nodenumber":0,"id":null,"cluster":"z"},
{"hostname":"wolk-1-gc-us-west1-datastore","dns":"c1","project":"us-west1-wlk","datacenter":"us-west1-a","publicip":"35.247.12.108","cloudprovider":"gc","consensus":true,"nodenumber":1,"id":null,"cluster":"z"},
{"hostname":"wolk-2-gc-us-west1-datastore","dns":"c2","project":"us-west1-wlk","datacenter":"us-west1-a","publicip":"","cloudprovider":"gc","consensus":true,"nodenumber":2,"id":null,"cluster":"w","knode":1},
{"hostname":"wolk-3-gc-us-west1-datastore","dns":"c3","project":"us-west1-wlk","datacenter":"us-west1-a","publicip":"34.83.135.112","cloudprovider":"gc","consensus":true,"nodenumber":3,"id":null,"cluster":"w"},
{"hostname":"wolk-4-gc-us-west1-datastore","dns":"c4","project":"us-west1-wlk","datacenter":"us-central","publicip":"","cloudprovider":"gc","consensus":true,"nodenumber":4,"id":null,"cluster":"c","knode":1},
{"hostname":"wolk-5-gc-europe-west3-datastore","dns":"c5","project":"us-west1-wlk","datacenter":"us-central","publicip":"35.198.123.24","cloudprovider":"gc","consensus":true,"nodenumber":5,"id":null,"cluster":"c"},
{"hostname":"wolk-6-gc-asia-east1-datastore","dns":"c6","project":"us-west1-wlk","datacenter":"us-east","publicip":"35.201.162.225","cloudprovider":"gc","consensus":true,"nodenumber":6,"id":null,"cluster":"e","knode":1},
{"hostname":"wolk-7-gc-asia-east1-datastore","dns":"c7","project":"us-west1-wlk","datacenter":"us-east","publicip":"34.80.96.150","cloudprovider":"gc","consensus":true,"nodenumber":7,"id":null,"cluster":"e"}
]
