---
- name: Install puppet repo
  gather_facts: No
  hosts: all

  tasks:
    - name: Add Puppet Labs GPG key.
      rpm_key:
        key: https://yum.puppetlabs.com/RPM-GPG-KEY-puppetlabs
        state: present

    - name: Add Puppet Labs repositories.
      package: name={{ puppet_yum_rpm }} state=present
