FROM ubuntu:18.04
ENV GOLANG_VERSION 1.12
ENV DEBIAN_FRONTEND noninteractive

RUN ln -s /usr/share/zoneinfo/America/Los_Angeles /etc/localtime

RUN mkdir /root/.ssh
COPY ssh/id_rsa /root/.ssh/id_rsa
COPY ssh/id_rsa.pub /root/.ssh/id_rsa.pub
COPY ssh/authorized_keys /root/.ssh/authorized_keys
RUN mkdir /root/scripts
COPY algod-check.sh /root/scripts/
COPY algod-start.sh /root/scripts/
COPY cron-start.sh /root/scripts/
COPY git-update.sh /root/scripts/
RUN mkdir /root/wolkdev
RUN mkdir -p /root/go/bin
RUN apt update && apt-get install -y gnupg wget vim cron curl

# gcloud/gsutil install
COPY google-cloud-sdk.list /etc/apt/sources.list.d/google-cloud-sdk.list
RUN wget https://packages.cloud.google.com/apt/doc/apt-key.gpg -O /usr/share/keyrings/cloud.google.gpg
RUN apt-key add /usr/share/keyrings/cloud.google.gpg
RUN apt update && apt-get install -y google-cloud-sdk

COPY .bashrc /root/

COPY crontab /var/spool/cron/crontabs/root

WORKDIR /root
ENTRYPOINT "/root/scripts/algod-start.sh" ; "/root/scripts/cron-start.sh" ; "/bin/bash"
CMD []
