apiVersion: apps/v1
kind: Deployment
metadata:
  name: x5-3
  labels:
    app: x5-3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: x5-3
  template:
    metadata:
      labels:
        app: x5-3
    spec:
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: x5-3
        image: gcr.io/europe-west3-wlk/wolkinc/cloudstore3:201910181400
        imagePullPolicy: IfNotPresent
        env:
          - name: CONSENSUSIDX
            value: "5"
          - name: NETWORKID
            value: "1571432068"
          - name: CEPHCLUSTER
            value: "x"
          - name: HTTPPORT
            value: "3085"
          - name: P2PPORT
            value: "33305"
          - name: RPCPORT
            value: "12905"
        ports:
        - name: https-stage3
          containerPort: 3085
        - name: p2p-stage3
          containerPort: 33305
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
      # if hostNetwork: false, the "rbd map" command hangs, see https://github.com/rook/rook/issues/2021
      hostNetwork: true
