apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2019-08-23T19:51:50Z"
  generation: 19
  labels:
    app: z0-2
  name: z0-2
  namespace: default
  resourceVersion: "2177325"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/z0-2
  uid: 72cf8640-c5df-11e9-b86f-42010a8a00c9
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: z0-2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: z0-2
    spec:
      containers:
      - env:
        - name: CONSENSUSIDX
          value: "0"
        - name: NETWORKID
          value: "1565809380"
        - name: CEPHCLUSTER
          value: z
        - name: HTTPPORT
          value: "2080"
        - name: P2PPORT
          value: "32000"
        - name: RPCPORT
          value: "11900"
        image: gcr.io/us-west1-wlk/wolkinc/cloudstore2z:201908221600
        imagePullPolicy: IfNotPresent
        name: z0-2
        ports:
        - containerPort: 2080
          name: https-stage2
          protocol: TCP
        - containerPort: 32000
          name: p2p-stage2
          protocol: TCP
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
        securityContext:
          privileged: true
          procMount: Default
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirstWithHostNet
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2019-08-23T19:51:50Z"
    lastUpdateTime: "2019-08-23T19:51:52Z"
    message: ReplicaSet "z0-2-8ddb55c5" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2019-08-23T21:53:36Z"
    lastUpdateTime: "2019-08-23T21:53:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 19
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
